.class public final Ld/b/b/a/c/a/a/ma;
.super Ld/b/b/a/c/a/f;
.source ""


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Ld/b/b/a/c/a/k;",
        ">",
        "Ld/b/b/a/c/a/f<",
        "TR;>;"
    }
.end annotation


# instance fields
.field public final a:Lcom/google/android/gms/common/api/internal/BasePendingResult;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lcom/google/android/gms/common/api/internal/BasePendingResult<",
            "TR;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Ld/b/b/a/c/a/g;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ld/b/b/a/c/a/g<",
            "TR;>;)V"
        }
    .end annotation

    invoke-direct {p0}, Ld/b/b/a/c/a/f;-><init>()V

    instance-of v0, p1, Lcom/google/android/gms/common/api/internal/BasePendingResult;

    if-eqz v0, :cond_0

    check-cast p1, Lcom/google/android/gms/common/api/internal/BasePendingResult;

    iput-object p1, p0, Ld/b/b/a/c/a/a/ma;->a:Lcom/google/android/gms/common/api/internal/BasePendingResult;

    return-void

    :cond_0
    new-instance p1, Ljava/lang/IllegalArgumentException;

    const-string v0, "OptionalPendingResult can only wrap PendingResults generated by an API call."

    invoke-direct {p1, v0}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw p1
.end method


# virtual methods
.method public final a(JLjava/util/concurrent/TimeUnit;)Ld/b/b/a/c/a/k;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    iget-object v0, p0, Ld/b/b/a/c/a/a/ma;->a:Lcom/google/android/gms/common/api/internal/BasePendingResult;

    invoke-virtual {v0, p1, p2, p3}, Lcom/google/android/gms/common/api/internal/BasePendingResult;->a(JLjava/util/concurrent/TimeUnit;)Ld/b/b/a/c/a/k;

    move-result-object p1

    return-object p1
.end method

.method public final a(Ld/b/b/a/c/a/g$a;)V
    .locals 1

    iget-object v0, p0, Ld/b/b/a/c/a/a/ma;->a:Lcom/google/android/gms/common/api/internal/BasePendingResult;

    invoke-virtual {v0, p1}, Lcom/google/android/gms/common/api/internal/BasePendingResult;->a(Ld/b/b/a/c/a/g$a;)V

    return-void
.end method

.method public final a(Ld/b/b/a/c/a/l;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ld/b/b/a/c/a/l<",
            "-TR;>;)V"
        }
    .end annotation

    iget-object v0, p0, Ld/b/b/a/c/a/a/ma;->a:Lcom/google/android/gms/common/api/internal/BasePendingResult;

    invoke-virtual {v0, p1}, Lcom/google/android/gms/common/api/internal/BasePendingResult;->a(Ld/b/b/a/c/a/l;)V

    return-void
.end method
